import type { Metadata } from "next";
import StoreProvider from "./StoreProvider";
import "./globals.css";
import { Poppins, Orbitron, Dancing_Script, Space_Grotesk } from 'next/font/google'
import { Toaster } from "@/components/ui/sonner"
import GlobalModal from "@/components/GlobalModal"

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins',
})

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-space-grotesk',
})

const dancingScript = Dancing_Script({
  subsets: ['latin'],
  variable: '--font-dancing-script',
})

const orbitron = Orbitron({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-orbitron',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import NextTopLoader from "nextjs-toploader";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${spaceGrotesk.variable} ${poppins.variable} ${orbitron.variable} ${dancingScript.variable}`}>
      <body
        className="bg-background font-sans" >
        <StoreProvider>
          <NextTopLoader
            color="#2563eb"
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
            shadow="0 0 10px #2563eb,0 0 5px #2563eb"
            zIndex={99999}
          />
          {children}
          <Toaster />
          <GlobalModal />
        </StoreProvider>
      </body>
    </html>
  )
}
